### PR TITLE
oe_funs(), close #54

### LINKED ISSUE #54: Replace osmext_ with oe_
To be concise.

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Superseded by #56

**Comment by agila5** [comment]
> Superseded by #56

So we can close this PR?

**Comment by Robinlovelace** [comment]
Not quite. I think we should merge this one to master after the vignettes PR is merged into this branch for educational purposes.

**Comment by Robinlovelace** [comment]
When that has happened this branch can be merged. I'll mark it as read for review now anyway... But please merge the other PR first, assuming you're happy with it (I think you will be : ).

**Comment by Robinlovelace** [comment]
Ready to merge @agila5 ?

**Pull request merged**
